### ISSUE TITLE
Support creating PRs in other repos

### ISSUE THREAD

**Issue by alejandrohdezma** [peter-evans/create-pull-request#105]
### Subject of the issue

It would be ideal to support creating PRs (using a custom personal access token) to remote repositories, using the `git remote` information.

### Steps to reproduce

Given a workflow like:

```yml
on: [push]

jobs:
  create-pr-on-remote-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repository: remote_owner/remote_repo
      - run: 'echo "v1.0" > .version'
      - uses: peter-evans/create-pull-request@v2.2.0
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          branch: auto-update-workflows-docs
```

I would expect:

✅ Creates PR in remote repository

but

❌ Tries to create PR in workflow's repo:

```
Pull request branch to create or update set to 'create-pull-request/patch'
Configured git committer as 'GitHub <noreply@github.com>'
Configured git author as 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
Uncommitted changes found. Adding a commit.
Pull request branch 'create-pull-request/patch' does not exist yet
Created branch 'create-pull-request/patch'
Pushing pull request branch to 'origin/create-pull-request/patch'

Traceback (most recent call last):
  File "/home/runner/work/_actions/peter-evans/create-pull-request/v2.2.0/dist/src/create_pull_request.py", line 174, in <module>
    repo.git.push("--force", repo_url, f"HEAD:refs/heads/{branch}")
  File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/git/cmd.py", line 551, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/git/cmd.py", line 1020, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/git/cmd.py", line 831, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)

git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git push --force ***github.com/current_owner/current_repo HEAD:refs/heads/create-pull-request/patch
  stderr: 'To https://github.com/current_owner/current_repo
 ! [remote rejected] HEAD -> create-pull-request/patch (shallow update not allowed)

error: failed to push some refs to '***github.com/current_owner/current_repo''

##[error]The process '/opt/hostedtoolcache/Python/3.8.1/x64/bin/python' failed with exit code 1

##[error]Node run failed with exit code 1
```

**Comment by peter-evans** [comment]
Released and updated `v2`. Thanks!
