### ISSUE TITLE
[v1] create-pull-request action suddenly stop working

### ISSUE THREAD

**Issue by gtrias** [peter-evans/create-pull-request#125]
### Subject of the issue

We have been using create-pull-request action until 16th febrary without any problem. But suddenly it stopped working with this error while running `create-pull-request.py`, We didn't touched anything related with github actions which can cause this error so idk where to start debugging. Any idea on how to fix it?

```
2020-02-18T14:06:06.9197382Z ##[group]Run peter-evans/create-pull-request@v1
2020-02-18T14:06:06.9197523Z with:
2020-02-18T14:06:06.9198054Z   token: ***
2020-02-18T14:06:06.9198154Z   title: Automatic i18n files update
2020-02-18T14:06:06.9198271Z   body: I18n files need an update
2020-02-18T14:06:06.9198394Z   commit-message: Update i18n files (automatic commit)
2020-02-18T14:06:06.9198514Z   branch-suffix: none
2020-02-18T14:06:06.9198626Z   branch: auto_feature/i18n
2020-02-18T14:06:06.9198745Z ##[endgroup]
2020-02-18T14:06:07.3017049Z [command]pip install --requirement /home/runner/work/_actions/peter-evans/create-pull-request/v1/dist/src/requirements.txt
2020-02-18T14:06:08.0258290Z Collecting GitPython==3.0.5
2020-02-18T14:06:08.0967103Z   Downloading GitPython-3.0.5-py3-none-any.whl (455 kB)
2020-02-18T14:06:08.2418948Z Collecting PyGithub==1.44.1
2020-02-18T14:06:08.2576614Z   Downloading PyGithub-1.44.1.tar.gz (110 kB)
2020-02-18T14:06:08.5860870Z Collecting gitdb2>=2.0.0
2020-02-18T14:06:08.6000136Z   Downloading gitdb2-3.0.2-py2.py3-none-any.whl (63 kB)
2020-02-18T14:06:08.6515068Z Collecting deprecated
2020-02-18T14:06:08.6653991Z   Downloading Deprecated-1.2.7-py2.py3-none-any.whl (8.3 kB)
2020-02-18T14:06:08.7260746Z Collecting pyjwt
2020-02-18T14:06:08.7397236Z   Downloading PyJWT-1.7.1-py2.py3-none-any.whl (18 kB)
2020-02-18T14:06:08.8242948Z Collecting requests>=2.14.0
2020-02-18T14:06:08.8391678Z   Downloading requests-2.22.0-py2.py3-none-any.whl (57 kB)
2020-02-18T14:06:08.9056093Z Collecting six
2020-02-18T14:06:08.9196720Z   Downloading six-1.14.0-py2.py3-none-any.whl (10 kB)
2020-02-18T14:06:08.9461510Z Collecting smmap2>=2.0.0
2020-02-18T14:06:08.9775482Z   Downloading smmap2-2.0.5-py2.py3-none-any.whl (24 kB)
2020-02-18T14:06:09.0117233Z Collecting wrapt<2,>=1.10
2020-02-18T14:06:09.0252271Z   Downloading wrapt-1.12.0.tar.gz (27 kB)
2020-02-18T14:06:09.3018030Z Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
2020-02-18T14:06:09.3167536Z   Downloading urllib3-1.25.8-py2.py3-none-any.whl (125 kB)
2020-02-18T14:06:09.3880363Z Collecting certifi>=2017.4.17
2020-02-18T14:06:09.4019778Z   Downloading certifi-2019.11.28-py2.py3-none-any.whl (156 kB)
2020-02-18T14:06:09.4559740Z Collecting chardet<3.1.0,>=3.0.2
2020-02-18T14:06:09.4702517Z   Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
2020-02-18T14:06:09.5368052Z Collecting idna<2.9,>=2.5
2020-02-18T14:06:09.5508978Z   Downloading idna-2.8-py2.py3-none-any.whl (58 kB)
2020-02-18T14:06:09.6190545Z Installing collected packages: smmap2, gitdb2, GitPython, wrapt, deprecated, pyjwt, urllib3, certifi, chardet, idna, requests, six, PyGithub
2020-02-18T14:06:09.8771087Z     Running setup.py install for wrapt: started
2020-02-18T14:06:11.1638639Z     Running setup.py install for wrapt: finished with status 'done'
2020-02-18T14:06:11.5781798Z     Running setup.py install for PyGithub: started
2020-02-18T14:06:11.9628815Z     Running setup.py install for PyGithub: finished with status 'done'
2020-02-18T14:06:11.9829082Z Successfully installed GitPython-3.0.5 PyGithub-1.44.1 certifi-2019.11.28 chardet-3.0.4 deprecated-1.2.7 gitdb2-3.0.2 idna-2.8 pyjwt-1.7.1 requests-2.22.0 six-1.14.0 smmap2-2.0.5 urllib3-1.25.8 wrapt-1.12.0
2020-02-18T14:06:12.1629645Z [command]python /home/runner/work/_actions/peter-evans/create-pull-request/v1/dist/src/create-pull-request.py
2020-02-18T14:06:12.2120813Z Traceback (most recent call last):
2020-02-18T14:06:12.2122695Z   File "/home/runner/work/_actions/peter-evans/create-pull-request/v1/dist/src/create-pull-request.py", line 9, in <module>
2020-02-18T14:06:12.2123400Z     from git import Repo
2020-02-18T14:06:12.2124341Z   File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/git/__init__.py", line 38, in <module>
2020-02-18T14:06:12.2124899Z     from git.exc import *                       # @NoMove @IgnorePep8
2020-02-18T14:06:12.2125835Z   File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/git/exc.py", line 9, in <module>
2020-02-18T14:06:12.2126739Z     from git.compat import UnicodeMixin, safe_decode, string_types
2020-02-18T14:06:12.2127627Z   File "/opt/hostedtoolcache/Python/3.8.1/x64/lib/python3.8/site-packages/git/compat.py", line 16, in <module>
2020-02-18T14:06:12.2128160Z     from gitdb.utils.compat import (
2020-02-18T14:06:12.2128955Z ModuleNotFoundError: No module named 'gitdb.utils.compat'
2020-02-18T14:06:12.2177962Z ##[error]The process 'python' failed with exit code 1
2020-02-18T14:06:12.2293630Z ##[error]Node run failed with exit code 1
```

### Steps to reproduce

Our relevant github action config is:

```
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: 'Automatic i18n files update'
        body: 'I18n files need an update'
        commit-message: 'Update i18n files (automatic commit)'
        branch-suffix: none
        branch: auto_feature/i18n
```

**Comment by gtrias** [comment]
Using v2 seems to work properly :)

**Comment by peter-evans** [comment]
Just tested and I'm seeing the same error. I haven't touched `v1` for a while so it looks like there is some problem with the Python dependencies.

There are *many* fixes and improvements in `v2`, so updating to `v2` is the best solution here.

**Comment by peter-evans** [comment]
I've hotfixed `v1` by updating the dependencies, but for anyone finding this issue please update to `v2`. There is a [short guide here](https://github.com/peter-evans/create-pull-request/blob/master/docs/updating.md).

**Comment by gtrias** [comment]
Thanks @peter-evans !!

**Comment by Harmon758** [comment]
See https://github.com/gitpython-developers/GitPython/issues/983.

**Comment by peter-evans** [comment]
Good to know the background. Thanks @Harmon758
