### ISSUE TITLE
fatal: --local can only be used inside a git repository

### ISSUE THREAD

**Issue by hildebro** [peter-evans/create-pull-request#138]
### Subject of the issue
I'm trying to automatically add a pull request when a certain set of branches are updated. However, my workflow is throwing this exception:

```
Successfully installed GitPython-3.0.8 PyGithub-1.46 certifi-2019.11.28 chardet-3.0.4 deprecated-1.2.7 gitdb2-3.0.2 idna-2.9 pyjwt-1.7.1 requests-2.23.0 smmap2-2.0.5 urllib3-1.25.8 wrapt-1.12.0
/usr/bin/git config --local --name-only --get-regexp http.https://github.com/.extraheader ^AUTHORIZATION:
fatal: --local can only be used inside a git repository
/opt/hostedtoolcache/Python/3.8.2/x64/bin/python /home/runner/work/_actions/peter-evans/create-pull-request/v2/dist/cpr/create_pull_request.py
Traceback (most recent call last):
  File "/home/runner/work/_actions/peter-evans/create-pull-request/v2/dist/cpr/create_pull_request.py", line 116, in <module>
    repo = Repo(path)
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/git/repo/base.py", line 181, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /home/runner/work/software/software
##[error]The process '/opt/hostedtoolcache/Python/3.8.2/x64/bin/python' failed with exit code 1
```

### Steps to reproduce
The following workflow file was triggered by pushing to `lokalise/de`

```
on:
  push:
    branches:
      - 'lokalise/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create pull request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ github.head_ref }}
          title: ${{ github.head_ref }}
          body: This is an auto-generated PR that updates localization files
          branch: ${{ github.head_ref }}

```

**Comment by peter-evans** [comment]
Hi @hildebro 

There are two things missing. Firstly, you need an `actions/checkout` step otherwise there is no git repository to work with. Secondly, the changes that are being pull requested should be made *during* the workflow. Please see the documentation and examples to understand how the action works.

https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#how-the-action-works
https://github.com/peter-evans/create-pull-request/blob/master/docs/examples.md
