### ISSUE TITLE
Download artifiacts, -- local can only run in git repository error

### ISSUE THREAD

**Issue by aminya** [peter-evans/create-pull-request#161]
### Subject of the issue

I have an action that uploads a whole git repository and then downloads it for creating a PR. However, the create-pr bot gives an error:
```
/usr/bin/git config --local --name-only --get-regexp http.https://github.com/.extraheader ^AUTHORIZATION:
fatal: --local can only be used inside a git repository
/opt/hostedtoolcache/Python/3.8.2/x64/bin/python /home/runner/work/_actions/peter-evans/create-pull-request/v2/dist/cpr/create_pull_request.py
Traceback (most recent call last):
  File "/home/runner/work/_actions/peter-evans/create-pull-request/v2/dist/cpr/create_pull_request.py", line 116, in <module>
    repo = Repo(path)
  File "/opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/git/repo/base.py", line 181, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /home/runner/work/Example.jl/Example.jl
##[error]The process '/opt/hostedtoolcache/Python/3.8.2/x64/bin/python' failed with exit code 1
```

### Steps to reproduce
https://github.com/aminya/Example.jl/actions/runs/81369735

The artifacts has the whole repo: https://github.com/aminya/Example.jl/suites/608063252/artifacts/4598275

**Comment by aminya** [comment]
I fixed the problem by adding a move command:
```
      - name: Move the content of the directory to the root
        run: |
          mv -v artifact/* ./
          mv -v artifact/.[^.]* ./
```
